### ISSUE TITLE
how to create annotation files

### ISSUE THREAD

**Issue by hufanglq** [RJWANGbioinfo/APAlyzer#1]
This is a good job! I want to know how to create the refUTRraw, dfIPA and dfLE files from other genome or GTF, refFlat format files.

**Comment by RJWANGbioinfo** [comment]
Hi @hufanglq ,

Thanks for your feedback.
In the current version, APAlyzer only supports creat refUTRraw from polyA_DB3:
http://exon.umdnj.edu/polya_db/v3/misc/download.php

We'll add the extract function for converting GTF to refUTRraw in the next update of APAlyzer.

**Comment by RJWANGbioinfo** [comment]
Hi @hufanglq 
The new function `GTF2PAS` ,has been added to the version 1.2.1.
You can now creat your reference through 
```
PASREF=PAS2GEF(GTFfile)	
refUTRraw=PASREF$refUTRraw
dfIPA=PASREF$dfIPA
dfLE=PASREF$dfLE
```
