### ISSUE TITLE
Confused about the interpretion of output

### ISSUE THREAD

**Issue by Lyuzu** [RJWANGbioinfo/APAlyzer#11]
Hello! Thank you for creating the useful tool. The version 1.9.2  worked well on my data. I am confused about the adjusted p value threshold because when I set 0.05, no gene left and ~400 genes left when I just used normal p value. I was wondering If you have some suggestion for setting threshold. 
Another question is about the tutorial, as I marked, according to your paper, aUTR is longer than cUTR, and RE=log2(aUTR/cUTR), to my understanding, "UP" means that treat group has higher RE and more longer UTR which seems opposite to the marked sentence. 
At last, I am sorry for a basic question that how to determine the strand type of my data because different strand-type would produce different output. 
Thanks for any help!

![image](https://user-images.githubusercontent.com/42428287/151669720-184d121a-7a46-4d1b-b3a8-e660c22be05b.png)

**Comment by Lyuzu** [comment]
anybody has the same question with the "UP meaning"? I really confused whether I misunderstood the meaning

**Comment by RJWANGbioinfo** [comment]
@Lyuzu, thanks for your questions
1. p.adj is currently calculated using "fdr" through `p.adjust`, you can set `p_adjust_methods` in `APAdiff` to other methods ("holm", "hochberg", "hommel", "bonferroni", "BH", "BY")
2. thanks for pointing this, it should be _‘UP’ means aUTR abundance in the treatment group
 (‘KD’ in this case) is at least 5% lower than that in control_ . The doc has been updated accordingly

**Comment by Lyuzu** [comment]
@RJWANGbioinfo Thanks for your reply! I am still confused because from the definition, RE=log2(aUTR/cUTR), RED=(RE of treatment group) - (RE of control group), So RE>0 means RE of treatment is bigger than RE of control which indicating aUTR abundance  is higher and 3' UTR is longer in treatment group. In one word, to my understanding, "RE>0" ="UP" = "aUTR abundance higher" = "3'UTR longer". Could you please correct me or point out the false part ? It is really important. Thanks for any help!

**Comment by Lyuzu** [comment]
![image](https://user-images.githubusercontent.com/42428287/155930628-54d82ebe-6959-4d82-92ba-0b16b0c9bafd.png)
As the paper indicated, I think maybe only one sentence should be corrected in your doc, that is " UP means 3'UTR shortening, DN 3'UTR lengthening"-->"DN means 3'UTR shortening, UP 3'UTR lengthening".

**Comment by RJWANGbioinfo** [comment]
@Lyuzu , we have performed multiple updates after the paper's publication, in the current version:
UP: delta RE (RED) > 0, p< 0.05
DN: delta RE (RED) < 0, p< 0.05
And the doc and vignettes have been updated to be consistent with the paper in the new version now (ver 1.9.4)
