### ISSUE TITLE
PASEXP_IPA error: Line "contains a feature that do not have a positive length"

### ISSUE THREAD

**Issue by rbatorsky** [RJWANGbioinfo/APAlyzer#4]
Hello,

I am working with human data with the provided hg38 reference `hg38_REF.RData`.

After the code:
```
IPA_OUT=PASEXP_IPA(dfIPA, dfLE, flsall, nts=1)
```
I get the error:
```
Error: Line 207 contains a feature that do not have a positive length!
 Error in featureCounts(fls, annot.ext = UPref, strandSpecific = IPAstr,  : 
  No counts were generated.
```

Looking more closely at the reference data, there do appear to be intervals of negative length in the resulting dataframes:
UPref, DNref and LEref.  For example, in genes: NBPF20,NBPF19, NBPF26,NBPF9,NBPF8, SEC22B, NBPF10, TIMM23B, GOLGA6L9. 

I can add the following code to the function `PASEXP_IPA` to select only positive intervals, and the code will run.
```
    UPref = subset(UPref, UPref$End - UPref$Start > 0)
    DNref = subset(DNref, DNref$End - DNref$Start > 0)
    LEref = subset(LEref, LEref$End - LEref$Start > 0)
```

I would greatly appreciate any help in understanding if there is a problem with the reference data, or perhaps my understanding of what the code is doing here.

Thank you for your work on this useful tool!
Best,
Rebecca

**Comment by RJWANGbioinfo** [comment]
Hi @rbatorsky 

Thanks for reporting this!

This also has been reported by other users as well. The current error is due to our hg38 reference is created through lifting over from the hg19, I'll fix it in the next update.

For the hotfix, you can use your subset code for now.

Best,
Ruijia

**Comment by RJWANGbioinfo** [comment]
Hi @rbatorsky 
This interval issues in `hg38_REF.RData` and `mm10_REF.RData` have been fixed. Feel free to let me know if this works for you.

**Comment by rbatorsky** [comment]
Thank you for your attention to this! 
I see that you have updated the files, but unfortunately I am getting the same error as before:
```
Error: Line 207 contains a feature that do not have a positive length!
Error in featureCounts(fls, annot.ext = UPref, strandSpecific = IPAstr,  : 
  No counts were generated.
```

**Comment by RJWANGbioinfo** [comment]
Hi @rbatorsky ,

Just to confirm,  did you re-download hg38 reference using:
```
library(repmis)

URL="https://github.com/RJWANGbioinfo/PAS_reference_RData/blob/master/"
file="hg38_REF.RData"
source_data(paste0(URL,file,"?raw=True"))
```

**Comment by rbatorsky** [comment]
Yes, the code I'm using is basically directly from your helpful tutorial:

```
library(APAlyzer)
library(repmis)

flsall <-c("sample_hg38.bam")

URL="https://github.com/RJWANGbioinfo/PAS_reference_RData/blob/master/"
file="hg38_REF.RData"
source_data(paste0(URL,file,"?raw=True"))

# rename to follow tutorial
refUTRraw = refUTRraw_hg38
dfIPA = dfIPA_hg38
dfLE = dfLE_hg38

PASREF=REF4PAS(refUTRraw,dfIPA,dfLE)
UTRdbraw=PASREF$UTRdbraw

dfIPA=PASREF$dfIPA
dfLE=PASREF$dfLE


IPA_OUT=PASEXP_IPA(dfIPA, dfLE, flsall, nts=1)
```

Here is a small example dataset that I use:
https://tufts.box.com/s/g7wxf5ch8x7onwg57dyf94ut2ug3v8hy

Thanks again for your help.

**Comment by RJWANGbioinfo** [comment]
Hi @rbatorsky 

I've updated the hg38_REF.RData. It should be fixed this time. I've tested using your bam file. 
Please try it again.

**Comment by rbatorsky** [comment]
It's working now! Thanks again for your help.

**Comment by RJWANGbioinfo** [comment]
Np, closing this issue.
