### ISSUE TITLE
download_testbam() bam files not working

### ISSUE THREAD

**Issue by xxy103** [RJWANGbioinfo/APAlyzer#5]
The bam files downloaded from the download_testbam() seemed corrupted.

"[E::bgzf_read] Read block operation failed with error 33 after 0 of 4 bytes
[E::bam_hdr_read] Invalid BAM binary header
[main_samview] fail to read the header from "Testis_rep1.bam".
"

**Comment by RJWANGbioinfo** [comment]
Hi @xxy103 thanks for your feedback, this seems due to the internet issues. Could you try it one more time? Thx.
