### ISSUE TITLE
Paired-end reads were detected in single-end read library

### ISSUE THREAD

**Issue by shorthouse-mrc** [RJWANGbioinfo/APAlyzer#6]
Apologies for re-opening this issue. I am trying to run an IPA analysis on a paired end sequencing library. 

Previously I had run this by taking only the forward strand fastq file, however I am now attempting to use the "ThreeMostPairBam" tool included in the more recent update (which I have used on your test files successfully previously).

I have run ThreeMostPairBam using:

$ThreeMostPairBam(Bamfile, Outdir, StrandType = "forward-reverse")

Successfully generating .3most.bam files, however when passing these files to PASEXP_IPA I get the following error from subread:

ERROR: Paired-end reads were detected in single-end read library : Bamfile-Seq.3most.bam
No counts were generated.

Am I following the useage correctly? I have tested using "reverse-forward", and "NONE" StrandTypes but still get the same error.

**Comment by SUN-Changyu** [comment]
I am seeing the same ERROR message in the exact same scenario. After running ThreeMostPairBam, I am still getting an ERROR message with no counts generated. I set the strand type as "NONE" in both proc.

**Comment by PieraccioliM** [comment]
I have the same error message. Any suggestion to resolve this error?

**Comment by RJWANGbioinfo** [comment]
Hi @shorthouse-mrc , @SUN-Changyu  and @PieraccioliM ,
This issue has been fixed now in APAlyzer **v.1.7.2**:

**To update the APAlyzer version:**
```
BiocManager::install('RJWANGbioinfo/APAlyzer')
```

**To use 3'most bam file in PASEXP_IPA, the user need to set the `SeqType` to "ThreeMostPairEnd", for example:** 
```
ThreemostBamfile="test.3most.bam"
IPA_OUTraw=PASEXP_IPA(dfIPA, dfLE, ThreemostBamfile, Strandtype="forward", SeqType="ThreeMostPairEnd")
```

**Comment by PieraccioliM** [comment]
Hi @RJWANGbioinfo,
thanks for fixing the issue. I've tested on my data and it worked using SeqType="ThreeMostPairEnd" and not SeqType=="ThreeMostPairEnd". I realized it was a typo.

Thanks again for your help.

**Comment by RJWANGbioinfo** [comment]
@PieraccioliM  ah, thanks for pointing this out.
Glad it works for you^.^

**Comment by RJWANGbioinfo** [comment]
Close this issue since it has been fixed
